"""
Fixtures for regression tests.

Provides common test data and setup for regression testing.
"""

import pytest
import json


@pytest.fixture
def regression_workspace(tmp_path):
    """
    Create a complete workspace for regression testing.

    Returns:
        Path: Directory containing a minimal CMake project
    """
    project = tmp_path / "regression_project"
    project.mkdir()

    # Create minimal CMakeLists.txt
    cmake_file = project / "CMakeLists.txt"
    cmake_file.write_text(
        "cmake_minimum_required(VERSION 3.20)\n"
        "project(RegressionTest)\n"
        "add_executable(test main.cpp)\n"
    )

    # Create minimal source file
    main_file = project / "main.cpp"
    main_file.write_text(
        "#include <iostream>\n"
        "int main() {\n"
        '    std::cout << "Hello" << std::endl;\n'
        "    return 0;\n"
        "}\n"
    )

    return project


@pytest.fixture
def legacy_config_v1(tmp_path):
    """
    Create a legacy v1 configuration file.

    Returns:
        Path: Path to config file
    """
    config = """version: 1
project:
  name: legacy-project
  language: cpp

toolchains:
  - name: llvm-18
    type: llvm
    version: 18.1.8

build:
  generator: Ninja
  build_type: Release
"""
    config_file = tmp_path / "toolchainkit.yaml"
    config_file.write_text(config)
    return config_file


@pytest.fixture
def legacy_state_file(tmp_path):
    """
    Create a legacy state file.

    Returns:
        Path: Path to state file
    """
    state = {
        "version": "0.1.0",
        "toolchain_id": "llvm-18.1.8-linux-x64",
        "config_hash": "abc123def456",
        "bootstrap_time": "2024-01-01T00:00:00",
    }

    state_dir = tmp_path / ".toolchainkit"
    state_dir.mkdir(parents=True, exist_ok=True)

    state_file = state_dir / "state.json"
    state_file.write_text(json.dumps(state, indent=2))
    return state_file


@pytest.fixture
def known_good_cmake_toolchain(tmp_path):
    """
    Snapshot of known good CMake toolchain file.

    Used to detect unintentional format changes.

    Returns:
        Path: Path to expected toolchain file
    """
    cmake_content = """# Generated by ToolchainKit
# DO NOT EDIT - This file is automatically generated

cmake_minimum_required(VERSION 3.20)

# System configuration
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# Compiler configuration
set(CMAKE_C_COMPILER "/opt/toolchains/llvm-18/bin/clang")
set(CMAKE_CXX_COMPILER "/opt/toolchains/llvm-18/bin/clang++")

# Compiler flags
set(CMAKE_C_FLAGS_INIT "-fPIC")
set(CMAKE_CXX_FLAGS_INIT "-fPIC -stdlib=libc++")
"""

    output_file = tmp_path / "expected_toolchain.cmake"
    output_file.write_text(cmake_content)
    return output_file


@pytest.fixture
def sample_toolchain_metadata():
    """
    Sample toolchain metadata for testing.

    Returns:
        dict: Toolchain metadata dictionary
    """
    return {
        "name": "llvm-18",
        "type": "llvm",
        "version": "18.1.8",
        "platform": "linux-x64",
        "download_url": "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz",
        "sha256": "a3d5f6e8b9c4d7e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5",
        "size_bytes": 524288000,
    }
