"""
Test to verify regression test fixtures are functional.
"""

import pytest


@pytest.mark.regression
def test_fixtures_available(
    regression_workspace,
    legacy_config_v1,
    legacy_state_file,
    known_good_cmake_toolchain,
    sample_toolchain_metadata,
):
    """Verify all regression fixtures are accessible and functional."""
    # regression_workspace
    assert regression_workspace.exists()
    assert (regression_workspace / "CMakeLists.txt").exists()
    assert (regression_workspace / "main.cpp").exists()

    # legacy_config_v1
    assert legacy_config_v1.exists()
    assert legacy_config_v1.name == "toolchainkit.yaml"
    content = legacy_config_v1.read_text()
    assert "version: 1" in content

    # legacy_state_file
    assert legacy_state_file.exists()
    assert legacy_state_file.name == "state.json"

    # known_good_cmake_toolchain
    assert known_good_cmake_toolchain.exists()
    content = known_good_cmake_toolchain.read_text()
    assert "Generated by ToolchainKit" in content

    # sample_toolchain_metadata
    assert sample_toolchain_metadata["name"] == "llvm-18"
    assert sample_toolchain_metadata["type"] == "llvm"
    assert sample_toolchain_metadata["version"] == "18.1.8"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
